### PR TITLE
Cross platform

### PR DESCRIPTION
**Pull request by xovertheyearsx**
Let me know what you think. Any changes, fixes, or additions are welcome. 

I chose to use C since it's more straight forward and the source didn't contain any pure C++ code (also, I don't have much experience with C++). This removes the C++ keywords from the equation when attempting to compile the code in pure C. 

Theoretically, GCC can compile this as C or C++ even though I have not tested it. For windows, I used MinGW which is a tiny GCC tool kit for windows. MinGW is for Windows only and I figured it would be more practical than using a full on software suite for such a small and simple project. MinGW can be used to compile the source without any library dependencies.

I used only GCC to compile ALL the binaries on each system. The binaries should execute within their respective environments.

### CODE REVIEW

**Comment by foreshadow** [comment]
I am not familiar with os other than Windows. Is this folder `/bin/cp-darwin13.4.0-x86_64.dSYM` necessary for users and other developers? Or it is a temp directory?

Besides, there seems to be a long directory `bin/cp-darwin13.4.0-x86_64.dSYM/cp-darwin13.4.0-x86_64.dSYM/cp-darwin13.4.0-x86_64.dSYM/cp-darwin13.4.0-x86_64.dSYM/cp-darwin13.4.0-x86_64.dSYM/cp-darwin13.4.0-x86_64.dSYM/Contents/`. 

Another problem I found is that, on my Windows platform, with the command = `python {file}` the package works fine, but there seems to be an error when I changed it to `python -i {file}`. (it won't occur in the current version)

I think we can deal with the new features and additions after we publish the cross-platform edition. There are many issues waiting for us.

**Comment by xovertheyearsx** [comment]
bin/cp-darwin13.4.0-x86_64.dSYM/ is used for the debugging symbols on mac.

and i agree. im certain there are. i did my best to find the important ones first.

**Comment by foreshadow** [comment]
Besides, it's almost my exam week, and I might start working on a new version by mid July.

**Comment by xovertheyearsx** [comment]
let me know. im working on a revised version on my down time. pretty much working from the ground up on this one. just as a FYI, not sure if the new version has gone out. i never changed the version tag. not sure if thats the problem. i do know that atom isnt recieving the update though.

**Pull request merged**
